config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  post 'spotify/swap', to: "spotify#swap"
  post 'spotify/refresh', to: "spotify#refresh"

  resources :tips, only: [:create]

  devise_for :playlist_editors

  resources :djs, only: [:index, :new, :create]
  devise_for :djs, controllers: { passwords: 'djs/passwords' }

  resources :semesters, shallow: true do
    resources :freeform_shows
    resources :specialty_shows do
      patch 'deal', on: :member
    end
    resources :talk_shows
    get 'based_on/:model_id', action: :new, on: :new
  end

  resources :songs, only: [:find] do
    get :find, on: :collection
  end
  resources :trainees, shallow: true do 
    resources :djs, except: [:index, :new], shallow: true do
      resources :episodes, except: [:show] do
        resources :songs
        resources :sub_requests, only: [:new, :create]
      end
    end
  end
  resources :episodes, only: [] do
    get :on_and_upcoming, on: :collection
  end

  resources :sub_requests, except: [:new, :create]

  resources :signoffs
  resources :signoff_instances, only: [:index, :update] do
    get :public_affairs_logs, on: :collection
  end

  resources :setbreaks, only: [:update, :create, :destroy]

  root 'playlist#index'
  resources :playlist, only: [:index] do
    get :search, on: :collection
    get :archive, on: :collection
  end

  post 'spotify/swap', to: "spotify#swap"
  post 'spotify/refresh', to: "spotify#refresh"
  mount ActionCable.server => '/cable'
end

app/models/dj.rb
class Dj < ActiveRecord::Base
  include Person

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  include Authority::UserAbilities
  include Authority::Abilities
  rolify

  has_and_belongs_to_many :specialty_shows
  has_many :freeform_shows
  has_many :talk_shows

  has_many :episodes

  has_one :trainee
  
  serialize :roles, Array

  validates :name, :phone, :email, presence: true
  validates :website, format: {with: /(\Ahttp|\A\Z)/, message: "must start with “http://”"}

  with_options if: :um_affiliated? do |dj|
    dj.validates :umid, :um_dept, presence: true
    #dj.validates :umid, format: {with: /\A[0-9]{8}\Z/}
  end

  def semesters_count
    (freeform_shows.map(&:semester) + specialty_shows.map(&:semester))
      .uniq.count
  end

  def to_s
    dj_name.blank? ? first_name : dj_name
  end

  # TODO: Refactor to able_to_do_daytime_radio?
  def allowed_to_do_daytime_radio?
    return false if has_role? :no_daytime
    semesters_count > 1 || has_role?(:grandfathered_in)
  end

  def shows
    freeform_shows + specialty_shows + talk_shows
  end

  def website_name
    URI::parse(website || (return nil)).host.sub('www.','')
  end

  def image_url
    has_custom_picture? ? profile_picture : robot_picture_url
  end

  def has_custom_picture?
    false
  end

  def robot_picture_url
    "http://www.robohash.org/#{Digest::MD5.hexdigest(email)}?set=set3"
  end

end

app/controllers/djs/passwords_controller.rb
class Djs::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  def update
    self.resource = resource_class.reset_password_by_token(resource_params)
    yield resource if block_given?

    password_errors = resource.errors.to_h.slice(:password, :password_confirmation)
    if password_errors.empty?
      resource.unlock_access! if unlockable?(resource)
      flash_message = resource.active_for_authentication? ? :updated : :updated_not_active
      set_flash_message(:notice, flash_message) if is_flashing_format?
      sign_in(resource_name, resource)
      if resource.errors.empty?
        respond_with resource, location: after_resetting_password_path_for(resource)
      else
        redirect_to edit_dj_path(resource)
      end
    else
      resource.errors.clear
      password_errors.each do |err|
        resource.errors.add *err
      end
      respond_with resource
    end
  end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/djs_controller.rb
class DjsController < ApplicationController
  before_filter :authenticate_dj!, except: :show
  authorize_actions_for Dj, only: [:new, :create, :destroy]

  before_action :set_dj, only: [:show, :edit, :update, :destroy]

  # GET /djs
  # GET /djs.json
  def index
    @djs = Dj.all.order(name: :asc)

    respond_to do |format|
      format.html{
        authorize_action_for Dj
        render layout: "wide"
      }
      format.pdf{ @djs = @djs.select &:active }
      format.csv do 
        @djs = @djs.select &:active 
        headers['Content-Disposition'] = "attachment; filename=\"wcbn-djs-#{Time.zone.now.strftime "%F"}\""
        headers['Content-Type'] ||= 'text/csv'
      end
    end
  end

  # GET /djs/1
  # GET /djs/1.json
  def show
    @shows = @dj.shows
      .sort_by(&:semester)
      .reject {|x| x.semester.future?}
      .group_by(&:unambiguous_name)
    @recent_episodes = @dj.episodes.where("beginning < ?", Time.zone.now)
      .order(beginning: :desc).first(5)
  end

  # GET /djs/new
  def new
    @dj = Dj.new
  end

  # GET /djs/1/edit
  def edit
    authorize_action_for @dj
  end

  # POST /djs
  # POST /djs.json
  def create
    if params[:trainee_id].blank?
      @dj = Dj.new dj_params
      @dj.password = "#{Time.zone.now}"
    else
      trainee = Trainee.find(params[:trainee_id])
      @dj = Dj.new trainee.attributes.slice(*(Dj.column_names - ['id']))
      @dj.password ||= "#{trainee.created_at}"
    end

    respond_to do |format|
      if @dj.save
        if trainee
          trainee.mark_graduated(approved_by: current_dj,
                                 associated_dj_instance: @dj)
        end
        @dj.add_role(:grandfathered_in) if params[:grandfathered] == '1'
        @dj.send_reset_password_instructions

        format.html { redirect_to @dj, notice: "#{@dj.name} is now a WCBN DJ." }
        format.json { render :show, status: :created, location: @dj }
      else
        format.html { render :new }
        format.json { render json: @dj.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /djs/1
  # PATCH/PUT /djs/1.json
  def update
    authorize_action_for @dj
    respond_to do |format|
      if @dj.update(dj_params)
        format.html { redirect_to @dj, notice: 'Dj was successfully updated.' }
        format.json { respond_with_bip @dj }
      else
        format.html { render :edit }
        format.json { respond_with_bip @dj }
      end
    end
  end

  # DELETE /djs/1
  # DELETE /djs/1.json
  def destroy
    @dj.destroy
    respond_to do |format|
      format.html { redirect_to djs_url, notice: 'Dj was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dj
      show_assoc = [:freeform_shows, :specialty_shows, :talk_shows].map do |show|
        [show, :semester]
      end
      show_assoc << [:episodes, :show]
      @dj = Dj.includes(Hash[show_assoc]).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dj_params
      params.require(:dj).permit(:name, :phone, :email, :umid, :um_affiliation,
                                 :um_dept, :experience, :referral, :interests,
                                 :statement, :real_name_is_public, :dj_name,
                                 :website, :public_email, :about, :lists, :active)
    end
end

app/helpers/djs_helper.rb
module DjsHelper
  def interest_link(name)
    '<input type="button" class="interest-link" data-interest="'+name+'" value="'+
      name+'" />'
  end

  def interest_links(list)
    list.map{ |i| interest_link i }.join.html_safe
  end

  def needs_statement(trainee)
    trainee.um_affiliation == 'community' || !trainee.statement.blank?
  end

  def active_for_select(*selected_djs)
    active_djs = Dj.where(active: true).order(:name)
    selected = selected_djs.flatten.map{ |dj| dj.try(:id) }
    puts "selected = #{selected}"
    options_from_collection_for_select(active_djs, :id, :name, selected)
  end

  def abbr(affil)
    case affil
    when 'community' then 'C.\@ A.'
    when 'student' then 'S.'
    when 'faculty' then 'F./S.'
    when 'alumnus' then 'A.'
    end
  end

  def roles_for_roster(dj)
    current_semester_shows = dj.shows.select{ |x| x.semester == Semester.current }
    if current_semester_shows.empty?
      "Sub Only"
    else
      types = current_semester_shows
        .map {|x| x.class.name.underscore.humanize.titlecase}
        .uniq
      if types.length > 1
        (types.map{ |x| x.split(' ').first } * ', ') + ' Shows'
      else
        types.first
      end
    end
  end

  def profile_picture(dj)
    content_tag :img, nil, class: ["profile-pic", ('robot' unless dj.has_custom_picture?)], src: dj.image_url
  end

end

app/views/djs/_dj.html.haml
=link_to dj do
  .dj.with-profile-pic
    %div
      = profile_picture dj
    %div
      %p
        %span#dj-name="#{dj}"
        - if dj_signed_in? || dj.real_name_is_public
          %span.subtitle.italic{style: "display:inline-table"}
            = " (#{dj.dj_name.blank? ? dj.name.split(' ')[1..-1]*' ' : dj.name})"

app/views/djs/edit.html.haml
- title "Editing DJ &mdash; #{@dj}"

= form_for(@dj) do |f|

  %header#headline.with-profile-pic
    = profile_picture @dj
    %div
      %p.linear-field
        = f.label :dj_name, "DJ Name"
        = f.text_field :dj_name, placeholder: @dj.first_name
      %p.linear-field
        = f.label :name, "Real Name"
        = f.text_field :name

  %aside.thin-sidebar{style: "padding-top: 0;"}
    .linear-field
      = f.label :real_name_is_public, "Make my real name public?"
      = f.check_box :real_name_is_public
    %br
    .actions
      = f.submit "Save changes", data: {disable_with: "Saving..."}

  %article.with-thin-sidebar.with-right-sidebar
    %section
      .dj-info
        - if @dj.errors.any?
          .alert
            - @dj.errors.full_messages.each do |msg|
              %p= msg
        %ul
          %li.linear-field
            = f.label :website
            = f.text_field :website, placeholder: "optional"
          %li.linear-field
            = f.label :public_email
            = f.text_field :public_email, placeholder: "optional"
        %p.instructions
          The following fields are only visible to WCBN DJs. (UMID only visible to Exec Staff.)
        %ul
          %li.linear-field
            = f.label :phone 
            = f.phone_field :phone
          %li.linear-field
            = f.label :email 
            = f.email_field :email
          %li.linear-field
            = f.label :um_affiliation, "U-M Affiliation"
            = f.select :um_affiliation, options_for_select([['U-M Student', 'student'],
                ['U-M Faculty or Staff', 'faculty'],
                ['U-M Alumnus/a', 'alumnus'],
                ['Community Member', 'community']],
              @dj.um_affiliation)
          %li.linear-field
            =f.label :umid, "UMID Number"
            =f.text_field :umid
          %li.linear-field
            = f.label :um_dept, "U-M Department"
            = f.text_field :um_dept
      = f.label :about, "Your Bio"
      %div
        %p.instructions
          You can use 
          = link_to "Markdown", "http://daringfireball.net/projects/markdown/syntax", target: "_blank"
          for formatting.
        = f.text_area :about, class: "dj-about-textarea monospace"
    %aside.right-sidebar
      = f.label :lists, "Your Picks"
      %p.instructions
        E.g. best albums this year, favorite instruments, etc.
        %br
        Use Markdown to do it as follows, and put a blank line in between two lists.
      =preserve do
        %pre.code<
          :escaped
            # Top 5 Concerts I’ve Seen
            1. John Coltrane, A Love Supreme, live at Festival Mondial du Jazz Antibes, 26 July 1965
            2. The Grateful Dead, then “Warlocks,” at the first Acid Test, 27 November 1965
            3. Bob Dylan – Newport Folk Festival, 25 July 1965
            4. Jimi Hendrix at Woodstock
            5. The Beatles’ rooftop concert, 30 January 1969
      = f.text_area :lists, class: "dj-lists-textarea monospace"

app/views/djs/index.csv.erb
<%- headers = %w(Name Email Affiliation Roles) %>
<%= CSV.generate_line headers %>
<% @djs.each do |dj| %>
<%= raw CSV.generate_line [dj.name, dj.email, dj.um_affiliation, roles_for_roster(dj)] %>
<% end %>

app/views/djs/index.html.haml
- title "DJs"
- headline "WCBN DJs"
- subtitle link_to "Print phone list", djs_path( format: :pdf )

%p= link_to "Create new DJ", new_dj_path

%table.dj-roster
  %thead
    %td Active?
    %td ID
    %td.width4 Name
    %td.width3 UM Affiliation
    %td UMID
    %td Phone
    %td Email
    %td Last Signed In
  - @djs.each do |dj|
    %tr
      %td{class: ("accent" if !dj.active)}
        = best_in_place dj, :active, as: :checkbox
      %td=dj.id
      %td
        = link_to dj do
          =dj.to_s
        = " (#{dj.dj_name.blank? ? dj.name.split(' ')[1..-1]*' ' : dj.name})"
      %td
        = dj.um_dept
        = Person::AFFILIATION_NAMES[dj.um_affiliation]
      %td=dj.um_id
      %td=dj.phone
      %td=mail_to dj.email
      %td
        = time_ago_in_words(dj.last_sign_in_at) rescue "–"

app/views/djs/new.html.haml
- title "New DJ"

= form_for(@dj) do |f|

  %header#headline.with-profile-pic
    %h3{style: "margin-right: 1em"} Creating New DJ
    %div
      %p.linear-field
        = f.label :dj_name, "DJ Name"
        = f.text_field :dj_name
      %p.linear-field
        = f.label :name, "Real Name"
        = f.text_field :name

  %aside.thin-sidebar{style: "padding-top: 0;"}
    .linear-field
      = f.label :real_name_is_public, "Real name is public:"
      = f.check_box :real_name_is_public
    .linear-field
      = f.label :active, "Active for subbing:"
      = f.check_box :active
    .linear-field
      = f.label :grandfathered, "Can do daytime subs:"
      = check_box_tag "grandfathered"
    %br
    .actions
      = f.submit "Save changes", data: {disable_with: "Saving..."}

  %article.with-thin-sidebar.with-right-sidebar
    %section
      .dj-info
        - if @dj.errors.any?
          .alert
            - @dj.errors.full_messages.each do |msg|
              %p= msg
        %ul
          %li.linear-field
            = f.label :website
            = f.text_field :website, placeholder: "optional"
          %li.linear-field
            = f.label :public_email
            = f.text_field :public_email, placeholder: "optional"
        %p.instructions
          The following fields are only visible to WCBN DJs. (UMID only visible to Exec Staff.)
        %ul
          %li.linear-field
            = f.label :phone 
            = f.phone_field :phone
          %li.linear-field
            = f.label :email 
            = f.email_field :email
          %li.linear-field
            = f.label :um_affiliation, "U-M Affiliation"
            = f.select :um_affiliation, options_for_select([['U-M Student', 'student'],
                ['U-M Faculty or Staff', 'faculty'],
                ['U-M Alumnus/a', 'alumnus'],
                ['Community Member', 'community']],
              @dj.um_affiliation)
          %li.linear-field
            =f.label :umid, "UMID Number"
            =f.text_field :umid
          %li.linear-field
            = f.label :um_dept, "U-M Department"
            = f.text_field :um_dept
      = f.label :about, "Bio"
      %div
        %p.instructions
          You can use 
          = link_to "Markdown", "http://daringfireball.net/projects/markdown/syntax", target: "_blank"
          for formatting.
        = f.text_area :about, class: "dj-about-textarea monospace"
    %aside.right-sidebar
      = f.label :lists, "Picks"
      %p.instructions
        E.g. best albums this year, favorite instruments, etc.
        %br
        Use Markdown to do it as follows, and put a blank line in between two lists.
      =preserve do
        %pre.code<
          :escaped
            # Top 5 Concerts I’ve Seen
            1. John Coltrane, A Love Supreme, live at Festival Mondial du Jazz Antibes, 26 July 1965
            2. The Grateful Dead, then “Warlocks,” at the first Acid Test, 27 November 1965
            3. Bob Dylan – Newport Folk Festival, 25 July 1965
            4. Jimi Hendrix at Woodstock
            5. The Beatles’ rooftop concert, 30 January 1969
      = f.text_area :lists, class: "dj-lists-textarea monospace"

app/views/djs/show.html.haml
- title "#{@dj}"

-# DJ Activity is in the sidebar if the dj has about text written, and in the
-# main body if not.
- content_for :dj_activity do
  - unless @shows.empty? && @recent_episodes.empty?
    .dj-shows
      - @shows.each do |name, shows|
        %h4=name
        %ul
          - shows.each do |show|
            %li
              =link_to "#{show.semester.season}", show
              =raw show.time_string rescue raw "&nbsp;(cancelled)"
    .dj-recent-episodes
      %h4 Most Recent Shows
      - @recent_episodes.each do |ep|
        =link_to episode_songs_path(ep), {class: %w(dj-recent-episode showinfo)} do
          %b=ep.show.unambiguous_name
          %p=ep.date_string
      .rightalign= link_to "All Recent Shows".html_safe, dj_episodes_path(@dj)

%header#headline.with-profile-pic
  =profile_picture @dj
  %div
    %h2="#{@dj}"
    - if dj_signed_in? || @dj.real_name_is_public
      %p.subtitle.italic
        =@dj.name
        =" (real name is #{"not " unless @dj.real_name_is_public}public)" if dj_signed_in?
    %p.subtitle.dj-edit-link
      - if dj_signed_in? && @dj.updatable_by?(current_dj)
        =link_to "edit profile", edit_dj_path(@dj)
      - if current_dj == @dj
        •
        =link_to "change password", edit_dj_registration_path

%aside.thin-sidebar
  = content_for(:dj_activity) unless @dj.about.blank?

%article.with-thin-sidebar.with-right-sidebar
  %section
    - if @dj.trainee && dj_signed_in? && current_dj.can_read?(@dj.trainee)
      .rightalign.minustop= link_to "Training History", @dj.trainee
    - unless !dj_signed_in? && @dj.website.blank? && @dj.public_email.blank?
      .dj-info
        %ul
          - if dj_signed_in?
            %li
              UM Affiliation:&nbsp;
              = @dj.um_dept
              = Person::AFFILIATION_NAMES[@dj.um_affiliation]
            - if @dj.um_affiliated? && current_dj.has_role?(:superuser)
              %li
                UMID:
                = @dj.um_id
            %li
              Phone:
              = @dj.phone
            %li
              Email:
              = mail_to @dj.email
              %br
          - unless @dj.website.blank?
            %li
              URL:
              = link_to @dj.website_name, @dj.website
          - unless @dj.public_email.blank?
            %li
              = "#{"Public " if dj_signed_in?}Email:"
              = link_to @dj.public_email, "mailto://#{@dj.public_email}"
    .dj-about
      - unless @dj.about.blank?
        = markdown @dj.about
      - else
        %span.italic This DJ has not written a bio.
    - if @dj.about.blank?
      %div
        = content_for(:dj_activity)

  - unless @dj.lists.blank?
    %aside.right-sidebar
      .dj-lists
        = markdown @dj.lists