config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  post 'spotify/swap', to: "spotify#swap"
  post 'spotify/refresh', to: "spotify#refresh"

  resources :tips, only: [:create]

  devise_for :playlist_editors

  resources :djs, only: [:index, :new, :create]
  devise_for :djs, controllers: { passwords: 'djs/passwords' }

  resources :semesters, shallow: true do
    resources :freeform_shows
    resources :specialty_shows do
      patch 'deal', on: :member
    end
    resources :talk_shows
    get 'based_on/:model_id', action: :new, on: :new
  end

  resources :songs, only: [:find] do
    get :find, on: :collection
  end
  resources :trainees, shallow: true do 
    resources :djs, except: [:index, :new], shallow: true do
      resources :episodes, except: [:show] do
        resources :songs
        resources :sub_requests, only: [:new, :create]
      end
    end
  end
  resources :episodes, only: [] do
    get :on_and_upcoming, on: :collection
  end

  resources :sub_requests, except: [:new, :create]

  resources :signoffs
  resources :signoff_instances, only: [:index, :update] do
    get :public_affairs_logs, on: :collection
  end

  resources :setbreaks, only: [:update, :create, :destroy]

  root 'playlist#index'
  resources :playlist, only: [:index] do
    get :search, on: :collection
    get :archive, on: :collection
  end

  post 'spotify/swap', to: "spotify#swap"
  post 'spotify/refresh', to: "spotify#refresh"
  mount ActionCable.server => '/cable'
end

app/models/episode.rb
class Episode < ActiveRecord::Base
  include Authority::Abilities

  enum status: [:unassigned, :normal, :confirmed, :needs_sub_in_group,
                :needs_sub, :needs_sub_including_nighttime_djs, :overridden]
  serialize :sub_request_group

  belongs_to :show, polymorphic: true
  belongs_to :dj
  belongs_to :trainee
  has_many :songs, dependent: :restrict_with_exception
  has_many :sub_requests, dependent: :destroy
  has_many :setbreaks, dependent: :destroy

  def self.on_at(time)
    where(beginning: (time - 6.hours)..time).order(:beginning).last
  end

  def self.on_air
    on_at(Time.zone.now)
  end

  def self.starts_on_day (day)
    where(beginning: (day.at_beginning_of_day..day.tomorrow.at_beginning_of_day)).take
  end

  def past?
    Time.zone.now > beginning
  end

  def at
    if Time.zone.now > beginning
      ending
    else
      beginning
    end
  end

  def range
    beginning..ending
  end

  def reminder_email_time
    number_of_days_before = (0...6).include?(beginning.hour) ? 2 : 1
    (beginning - number_of_days_before.days).at_beginning_of_day + 9.hours
  end

  def subbed_for?
    (confirmed? || needs_sub? || needs_sub_including_nighttime_djs?) && dj != show.dj
  end

  def date_string
    "#{beginning.strftime("%A, %B %-d, %Y")}".html_safe
  end

  def just_time_string(html: true)
    dash = html ? '–'.html_safe : ' -- '
    "#{beginning.strftime("%l:%M")}#{dash}#{ending.strftime("%l:%M%P")}"
      .html_safe.gsub ' ', ''
  end

  def time_string
    date_string + "<span style=\"display:inline-block\">&nbsp;&nbsp;&nbsp;#{just_time_string}</span>".html_safe
  end

  def active_dj
    dj || show.dj
  end

  def nighttime?
    beginning.hour.between?(0,5)
  end

  def status_string
    case status
    when 'unassigned' then 'Unassigned'
    when 'normal' then "#{dj}"
    when 'confirmed' then "#{dj} &#x2713;".html_safe
    when /needs_sub/ then "#{dj}"
    when 'overridden' then "Overridden!"
    end
  end

  def dj_on_hook?
    unassigned? || SubRequest.where(episode: self).where.not(status: SubRequest.statuses[:confirmed]).any?
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_filter :authenticate!, except: [:index, :on_and_upcoming]
  authorize_actions_for Episode, except: [:index, :on_and_upcoming]
  before_action :set_episode, only: [:edit, :update]

  def index
    @dj = Dj.includes(episodes: [:sub_requests, show: [:dj, :semester]]).find(params[:dj_id])
    episodes = @dj.episodes.order(beginning: :desc).reject { |x| x.show.semester.future? }
    @future_episodes = episodes.reject(&:past?).reverse
    @past_episodes_by_semester = (episodes - @future_episodes).group_by { |x| x.show.semester }
  end

  def edit
    authorize_action_for @episode
    render layout: 'headline'
  end

  # PATCH/PUT /episodes/1
  # PATCH/PUT /episodes/1.json
  def update
    authorize_action_for @episode
    @episode.status = :confirmed
    respond_to do |format|
      if @episode.update(episode_params)
        format.html do
          path = if params[:episode].include?(:shadowed)
                   root_path 
                 else 
                   episode_songs_path(@episode)
                 end
          redirect_to path, notice: 'Episode was successfully updated.'
        end
        format.json { respond_with_bip @episode }
      else
        format.html { render :edit }
        format.json { respond_with_bip @episode }
      end
    end
  end

  def on_and_upcoming
    @standalone = true
    @on_air = Episode.on_air
    @future_episodes = Episode.includes(:dj, show: [:dj])
      .where(beginning: Time.zone.now..10.hours.since)
      .order(beginning: :asc)

    # For Tony's scraper
    @escaped_show_name = Rack::Utils.escape("#{@on_air.show.name} with #{@on_air.dj}") if params[:escaped_show_name]

    respond_to do |format|
      format.html do
        render layout: 'iframe'
      end
      format.json do
        render(text: @escaped_show_name)&& return if @escaped_show_name
        render
      end
    end

    expires_in 2.minutes, :public => true
    fresh_when last_modified: @on_air.beginning, public: true
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_episode
      @episode = Episode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def episode_params
      params.require(:episode).permit(:dj_id, :notes, :shadowed)
    end

    def authenticate!
      if playlist_editor_signed_in?
        authenticate_playlist_editor!
      else
        authenticate_dj!
      end
    end
end

app/helpers/episodes_helper.rb
module EpisodesHelper
  def with(ep, short:false)
    dj_name = link_to(ep.active_dj, ep.active_dj).html_safe
    case ep.show_type
    when "FreeformShow" then
      "with #{"Guest DJ" if ep.subbed_for?} #{dj_name}".html_safe
    when "SpecialtyShow" then
      "with rotating host #{dj_name}".html_safe
    when "TalkShow" then
      wcbn_pa = with = ""
      wcbn_pa = "a WCBN public affairs show" unless short
      your_or_guest = ep.subbed_for? ? "guest" : "your"
      with = "with #{your_or_guest} host, #{dj_name}" unless ep.show.dj.nil?
      raw wcbn_pa + " " + with
    end
  end
end

app/views/episodes/_episode.html.haml
%td{colspan: 6}
  .showinfo
    %h2=episode.show.name
    %p.with=with episode
    %p.time{data: {beginning: episode.beginning.strftime("%l:%M%P")}}=episode.time_string
  - if on_fm_computer?
    - t = episode.trainee
    - if t && episode.shadowed.nil?
      %h4#trainee-attendance-hdr.accent.nomargin.clickable Trainee? Click here!
      #trainee-attendance.hidden.padbottom
        %p.instructions
          %strong>=t.name
          , a DJ-in-training, is scheduled to do
          = t.episodes.select(&:shadowed).any? ? " an apprentice" : "stage-two training"
          with you today.  Give them some time to show up, then choose:
        .field-beginning
          = form_for episode do |f|
            = f.hidden_field :shadowed, value: true
            = f.submit "They’re here!"
        .field-ending
          = form_for episode do |f|
            = f.hidden_field :shadowed, value: false
            = f.submit "They’re not here!", data: {confirm: "You can’t undo this. Are you sure the trainee isn’t just running late?"}

app/views/episodes/_shownotes.html.haml
- if episode.show_type == "TalkShow"
  - instructions = "The FCC requires non-commercial stations to record the topics they cover in public affairs shows. Please click here and write a brief description of the day’s topics on “#{episode.show.name}.”"
- else
  - instructions = "Click here to add your show notes."

- editable ||= false
- longform ||= false
- if !episode.notes.nil? || editable
  .show-notes-box
    %h4 Show Notes:
    .show-notes{lang: 'en', class: ('longform' if longform)}
      - episode.notes ||= ''
      = best_in_place_if editable, episode, :notes, display_with: -> (notes) { markdown(notes)}, as: :textarea, place_holder: instructions

app/views/episodes/_upcoming_episodes.html.haml
- limit ||= nil
.on-and-upcoming
  %h4.small-caps-title On Air:
  - if @on_air
    = render @on_air
  - else
    %p.alert There is no show currently scheduled.
  - if !on_fm_computer? || @standalone
    = render('episodes/shownotes', episode: @on_air) if @on_air
    %h4.small-caps-title Up Next:
    - upcoming_episodes = @future_episodes
    - upcoming_episodes = upcoming_episodes.take(limit) if limit
    - upcoming_episodes.each do |ep|
      = render ep

app/views/episodes/edit.html.haml
- title "Editing Show Notes: #{@episode.show.unambiguous_name}"
- headline "Editing Show Notes: #{@episode.show.unambiguous_name}"
- subtitle raw "#{with @episode} on #{@episode.date_string}"

= form_for @episode do |f|
  .field
    = f.text_area :notes, style: "height: 40em"
  .actions
    = f.submit "Save show notes", data: {disable_with: "Saving..."}

app/views/episodes/index.html.haml
- title "#{@dj} — Recent Episodes"

%header#headline.with-profile-pic
  = profile_picture @dj
  -#%img.profile-pic{src: "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(@dj.email)}?d=identicon&s=200&f=y"}
  %div
    %h2="#{@dj}"
    - if dj_signed_in? || @dj.real_name_is_public
      %p.subtitle.italic
        =@dj.name
        =" (real name is #{"not " unless @dj.real_name_is_public}public)" if dj_signed_in?
    %p.subtitle.dj-edit-link=link_to "go to profile", dj_path(@dj)

%article
  -if dj_signed_in? && @future_episodes.any?
    .dj-all-episodes
      %h4 Upcoming Shows
      %p.instructions
        - if current_dj == @dj
          You can request a substitute for a show by clicking the&nbsp;
          %i.fa.fa-calendar-times-o
          &nbsp;icon.
        - if @future_episodes.map(&:sub_requests).flatten.reject(&:confirmed?).any?
          Active sub requests are indicated by the&nbsp;
          %i.fa.fa-exclamation-triangle
          &nbsp;icon.
      - @future_episodes.each do |ep|
        .dj-episode
          .showinfo
            %b=ep.show.unambiguous_name
            %p=ep.date_string
          .buttons
            - reqs = ep.sub_requests.reject(&:confirmed?)
            - if reqs.any?
              %p{title: "Go to active sub request"}
                = link_to reqs.first do
                  %i.fa.fa-exclamation-triangle
            - elsif current_dj.can_create? SubRequest, for: ep
              %p{title: "Request Sub"}
                = link_to new_episode_sub_request_path(ep) do
                  %i.fa.fa-calendar-times-o

  .dj-all-episodes
    - @past_episodes_by_semester.each do |semester, episodes|
      %h4.padtop= semester == Semester.current ? "Most Recent Shows" : semester.season
      .tiles
        - episodes.each do |ep|
          .dj-episode
            .showinfo
              %b=ep.show.unambiguous_name
              %p=ep.date_string
            .buttons
              = link_to "[#{ep.songs.count}]",
                episode_songs_path(ep)

app/views/episodes/on_and_upcoming.html.haml
= render "upcoming_episodes", limit: 3