config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  post 'spotify/swap', to: "spotify#swap"
  post 'spotify/refresh', to: "spotify#refresh"

  resources :tips, only: [:create]

  devise_for :playlist_editors

  resources :djs, only: [:index, :new, :create]
  devise_for :djs, controllers: { passwords: 'djs/passwords' }

  resources :semesters, shallow: true do
    resources :freeform_shows
    resources :specialty_shows do
      patch 'deal', on: :member
    end
    resources :talk_shows
    get 'based_on/:model_id', action: :new, on: :new
  end

  resources :songs, only: [:find] do
    get :find, on: :collection
  end
  resources :trainees, shallow: true do 
    resources :djs, except: [:index, :new], shallow: true do
      resources :episodes, except: [:show] do
        resources :songs
        resources :sub_requests, only: [:new, :create]
      end
    end
  end
  resources :episodes, only: [] do
    get :on_and_upcoming, on: :collection
  end

  resources :sub_requests, except: [:new, :create]

  resources :signoffs
  resources :signoff_instances, only: [:index, :update] do
    get :public_affairs_logs, on: :collection
  end

  resources :setbreaks, only: [:update, :create, :destroy]

  root 'playlist#index'
  resources :playlist, only: [:index] do
    get :search, on: :collection
    get :archive, on: :collection
  end

  post 'spotify/swap', to: "spotify#swap"
  post 'spotify/refresh', to: "spotify#refresh"
  mount ActionCable.server => '/cable'
end

app/models/song.rb
class Song < ActiveRecord::Base
  validates :name, :episode_id, presence: true
  validates_datetime :at,
    on_or_after: ->(t){ t.episode.beginning },
    before: ->(t){ Time.zone.now }

  belongs_to :episode

  after_create :post_information_to_icecast

  def post_information_to_icecast
    %w(hd mid hi)
      .each do |qual|
      Kernel.system "curl --max-time 0.5 --user admin:#{ENV['ICECAST_ADMIN_PASSWORD']}  \"http://floyd.wcbn.org:8000/admin/metadata?mount=/wcbn-#{qual}.mp3&mode=updinfo&song=#{Rack::Utils.escape metadata_string}\""
    end
  end

  def metadata_string
    "WCBN-FM: “#{name}”#{" by #{artist}" unless artist.blank?} – on #{episode.show.name} with #{episode.dj}"
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  before_action :set_song, only: [:update, :destroy]
  layout "headline"

  # GET /songs/find.json
  def find
    query = "(artist ILIKE :artist_name)" +
            "AND (#{params[:name].nil? ? "TRUE" : "name ILIKE :song_title"})" +
            "AND (#{params[:album].nil? ? "TRUE" : "album ILIKE :album_name"})" +
            "AND (album IS NOT NULL) AND (album != '')" +
            "AND (label IS NOT NULL) AND (label != '')"
    results = Song
      .where(query, {
          artist_name: "#{params[:artist]}%",
          song_title: "#{params[:name]}%",
          album_name: "#{params[:album]}%"
        })
      .order(at: :desc)

    case_transformation = params[:artist].case

    results = results.map do |r|
      unless r.name.case == case_transformation
        r = r.as_json
        r.each_pair do |key, val|
          r[key] = val.send case_transformation if val.is_a? String
        end
        r
      else
        r.as_json
      end
    end

    if !params[:name].nil?
      fields = %w(name album label year local)
    elsif !params[:album].nil?
      fields = %w(album label year local)
    else
      fields = %w(artist)
    end

    results.map! do |r|
      r.slice *fields
    end

    results.group_by &:itself

    respond_to do |format|
      format.json do
        render json: results
          .each_with_object(Hash.new(0)) { |o, h| h[o] += 1  }
          .sort_by { |k, v| -v  }
          .map(&:first)[0..4]
      end
    end
  end

  # GET /songs
  # GET /songs.json
  def index
    @episode = Episode.includes(:setbreaks, show: [:semester, :dj, episodes: [:dj, :show]]).find(params[:episode_id])
    #@songs = Song.all.sort_by(&:at).reverse
    @songs = @episode.songs
    @songs += @episode.setbreaks
    @songs = @songs.sort_by(&:at)
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)
    @episode = Episode.includes(show: [:semester, :dj]).find(params[:episode_id])
    @song.episode = @episode
    @song.at = unless params[:override_episode] == 'true'
                 Time.zone.now
               else
                 @song.episode.ending - 1.second
               end

    respond_to do |format|
      if (@song.at.between?( @song.episode.beginning, @song.episode.ending ) ||
          params[:override_episode] == 'true')
        if @song.save
          format.html { redirect_to controller: :playlist, action: :index }
          format.json { render :show, status: :created, location: @song }
        else
          format.html {
            flash[:alert] = @song.errors.full_messages
            session[:song] = @song
            redirect_to controller: :playlist, action: :index }
          format.json { render json: @song.errors, status: :unprocessable_entity }
        end
      else
        format.html {
          session[:song] = @song
          session[:confirm_episode] = true
          redirect_to controller: :playlist, action: :index
        }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.json { respond_with_bip @song }
      else
        format.json { respond_with_bip @song }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html {
        flash[:alert] = ["Song deleted"]
        redirect_to controller: :playlist, action: :index
      }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:name, :artist, :request, :album, :label,
                                   :year, :episode_id, :at, :local, :new)
    end
end

app/helpers/songs_helper.rb
module SongsHelper
  def message_if_episode_has_no_songs(episode)
    if episode.songs.empty?
      Haml::Engine.new(
"%tr
  %td.instructions{colspan: 6}
    = \"There are no songs recorded for #{h episode.show.unambiguous_name}\""
      ).render
    end
  end

  def just_time(time)
    time.strftime "%-l:%M %P"
  end
end

app/views/songs/_form.html.haml
= form_for [@on_air, @song] do |f|
  - if session[:confirm_episode]
    .alert
      Would you like to save this to the new show, or the old?
  - if @song.errors.any?
    #error_explanation
      %h2<
        = pluralize(@song.errors.count, "error")
        prohibited this song from being saved:
      %ul
        - @song.errors.full_messages.each do |msg|
          %li= msg
  .field.field-withflag
    = f.label :artist, "Artist"
    %br
    = f.text_field :artist, tabindex: 1, autofocus: true
  .field.field-flag
    = f.label :local, "Local?"
    %br
    = f.check_box :local, tabindex:7

  .field.field-withflag
    = f.label :name, "Song Title*"
    %br
    = f.text_field :name, tabindex: 2
  .field.field-flag
    = f.label :request, "Req?"
    %br
    = f.check_box :request, tabindex:7

  .field.field-withflag
    = f.label :album, "Album"
    %br
    = f.text_field :album, tabindex: 3
  .field.field-flag
    = f.label :new, "New?"
    %br
    = f.check_box :new, tabindex:8

  .field.field-label
    = f.label :label, "Label"
    %br
    = f.text_field :label, tabindex: 4
  .field.field-year
    = f.label :year, "Year"
    %br
    = f.number_field :year, tabindex: 5, autocomplete: 'off'
  -#.field
    -#%label Notes
    -#%br
    -#%textarea{rows: '3', tabindex: 7}
  = hidden_field_tag :override_episode
  .actions.and-clear
    - if session[:confirm_episode]
      = f.submit "Save song to #{@on_air.show.unambiguous_name}", data: { disable_with: 'Saving...' }, tabindex: 9
      = f.submit "Save song to #{@song.episode.show.unambiguous_name}", data: { disable_with: 'Saving...', previous_show: @song.episode.id},  tabindex: 8, id: "submit-to-previous-show", class: 'padtop'
    - else
      = f.submit "Save song", data: { disable_with: 'Saving...' }, tabindex: 8

app/views/songs/_song.html.haml
- path = song_path(song)
- can_bip = song.episode == @on_air && on_fm_computer?
%td.width1
  - if can_bip
    .delete-song=link_to '[x]', path, method: :delete, data: {confirm: "Are you sure you want to delete this song?"}
  -#.thin.time-col=song.at.strftime '%l:%M %P'
  .thin.time-col
    =best_in_place_if can_bip, song, :at, inner_class: "bip-sized", url: path, display_with: ->(x) {just_time x}, value: just_time(song.at), class: "sortable-at"
%td.width3
  =best_in_place_if can_bip, song, :artist, inner_class: "bip-sized", url: path
  %span.thin.accent=' (local)' if song.local
%td.width4<
  =best_in_place_if can_bip, song, :name, display_with: lambda {|str| '“' + str + '”' }, inner_class: "bip-sized", url: path
  %span.thin.accent=' (by request)' if song.request
%td.width3.italic
  =best_in_place_if can_bip, song, :album, inner_class: "bip-sized", url: path
  %span.thin.accent=' (new)' if song.new
%td.width2.thin=best_in_place_if can_bip, song, :label, inner_class: "bip-sized", url: path
%td.width1.thin=best_in_place_if can_bip, song, :year, inner_class: "bip-sized", url: path

app/views/songs/index.html.haml
- title "Playlist: #{@episode.show.unambiguous_name}"
- headline "Playlist: #{@episode.show.unambiguous_name}"
- subtitle raw "#{with @episode} on #{@episode.date_string}"
- if dj_signed_in? && current_dj.can_update?(@episode)
  - subtitle raw "<br />"
  - subtitle link_to "Edit show notes", edit_episode_path(@episode)
- back_link link_to "Back to Schedule", @episode.show.semester
- content_for :sidebar do
  .rightalign=link_to "All Episodes", @episode.show
  .tiles
    - @episode.show.episodes.order(beginning: :desc).select(&:past?).each do |episode|
      .showinfo.tile
        %p{class: ("highlight" if episode == @episode)}
          =link_to episode.date_string, episode_songs_path(episode)
        %p.with
          =with episode

= render 'episodes/shownotes', episode: @episode, longform: true

- unless @songs.empty?
  %table
    %thead
      %td Time
      %td Artist
      %td Song Title
      %td Album
      %td Label
      %td Year
    - @songs.each do |song|
      %tr
        = render song