config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  post 'spotify/swap', to: "spotify#swap"
  post 'spotify/refresh', to: "spotify#refresh"

  resources :tips, only: [:create]

  devise_for :playlist_editors

  resources :djs, only: [:index, :new, :create]
  devise_for :djs, controllers: { passwords: 'djs/passwords' }

  resources :semesters, shallow: true do
    resources :freeform_shows
    resources :specialty_shows do
      patch 'deal', on: :member
    end
    resources :talk_shows
    get 'based_on/:model_id', action: :new, on: :new
  end

  resources :songs, only: [:find] do
    get :find, on: :collection
  end
  resources :trainees, shallow: true do 
    resources :djs, except: [:index, :new], shallow: true do
      resources :episodes, except: [:show] do
        resources :songs
        resources :sub_requests, only: [:new, :create]
      end
    end
  end
  resources :episodes, only: [] do
    get :on_and_upcoming, on: :collection
  end

  resources :sub_requests, except: [:new, :create]

  resources :signoffs
  resources :signoff_instances, only: [:index, :update] do
    get :public_affairs_logs, on: :collection
  end

  resources :setbreaks, only: [:update, :create, :destroy]

  root 'playlist#index'
  resources :playlist, only: [:index] do
    get :search, on: :collection
    get :archive, on: :collection
  end

  post 'spotify/swap', to: "spotify#swap"
  post 'spotify/refresh', to: "spotify#refresh"
  mount ActionCable.server => '/cable'
end

app/models/freeform_show.rb
class FreeformShow < ActiveRecord::Base
  include Show

  belongs_to :dj
  validates :dj, presence: true

  def default_status
    :normal
  end

  def unambiguous_name
    if name == "Freeform"
      "Freeform w/ #{dj}"
    else
      name
    end
  end

  def alternate_host_name
    "guest DJ"
  end

  def with
    "with #{dj}"
  end

  def hosts
    [dj]
  end
end

app/controllers/freeform_shows_controller.rb
class FreeformShowsController < ApplicationController
  include ShowsController

  # GET /freeform_shows
  # GET /freeform_shows.json
  def index
    @freeform_shows = FreeformShow.all
  end

  # GET /freeform_shows/1
  # GET /freeform_shows/1.json
  def show
  end

  # GET /freeform_shows/new
  def new
    @freeform_show = FreeformShow.new
  end

  # GET /freeform_shows/1/edit
  def edit
    authorize_action_for @freeform_show
  end

  # POST /freeform_shows
  # POST /freeform_shows.json
  def create
    @freeform_show = FreeformShow.new(freeform_show_params)
    @freeform_show.dj_id = params[:freeform_show][:dj_id]
    @freeform_show.semester_id = params[:semester_id]

    @freeform_show.set_times_conditionally_from_params params[:freeform_show]

    respond_to do |format|
      if @freeform_show.save
        format.html do
          #session[:freeform_show] = {
            #weekday: @freeform_show.weekday,
            #beginning: @freeform_show.ending
          #}
          redirect_to edit_semester_path(@freeform_show.semester)
        end
      else
        format.html do
          flash[:alert] = @freeform_show.errors.full_messages
          session[:freeform_show] = @freeform_show
          redirect_to edit_semester_path(params[:semester_id])
        end
      end
    end
  end

  # PATCH/PUT /freeform_shows/1
  # PATCH/PUT /freeform_shows/1.json
  def update
    authorize_action_for @freeform_show

    unless params[:freeform_show][:dj_id].nil?
      @freeform_show.dj_id = params[:freeform_show][:dj_id]
    end
    @freeform_show.set_times_conditionally_from_params params[:freeform_show]

    respond_to do |format|
      if @freeform_show.update(freeform_show_params)
        format.html { redirect_to @freeform_show, notice: 'Freeform show was successfully updated.' }
        format.json { render :show, status: :ok, location: @freeform_show }
      else
        format.html { render :show }
        format.json { render json: @freeform_show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /freeform_shows/1
  # DELETE /freeform_shows/1.json
  def destroy
    @freeform_show.destroy
    respond_to do |format|
      format.html { redirect_to edit_semester_path(@freeform_show.semester), notice: 'Freeform show was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def active_record_find_includes
      { episodes: [:dj, show: [:dj]] }
    end
end

app/helpers/freeform_shows_helper.rb
module FreeformShowsHelper
  include ShowsHelper
end

app/views/freeform_shows/_form.html.haml
= form_for [@semester, @freeform_show] do |f|
  - if @freeform_show.errors.any?
    .alert
      - @freeform_show.errors.full_messages.each do |msg|
        %p= msg
  .field
    = f.label :name
    = f.text_field :name, tabindex: 10
  .field
    = f.label :description
    = f.text_area :description, {tabindex: 11, rows: 8}
  .field
    = f.label :website
    = f.text_field :website, tabindex: 12
  - if current_dj.can_create?(FreeformShow)
    .field
      = f.label :dj_id, 'DJ'
      %br
      = f.select :dj_id, active_for_select(f.object.dj), {}, tabindex: 13, class: 'chzn-select'
    .field
      = f.label :weekday
      = f.select :weekday, options_for_select(DateTime::DAYNAMES.map.with_index.to_a, f.object.weekday), {}, tabindex:14
    .field.field-beginning
      = f.label :beginning, 'Start'
      = f.time_field :beginning, value: format_time(f.object.beginning), tabindex: 15
    .field.field-ending
      = f.label :duration, raw('Duration&nbsp;(hrs)')
      = f.number_field :duration, step: 0.1, tabindex: 16
  .actions
    = f.submit 'Save freeform show', data: { disable_with: 'Saving...' }, tabindex: 17

app/views/freeform_shows/_freeform_show.html.haml
- if defined?(locals) && locals[:no_links]
  .show_name=freeform_show.name
  .show_with="with #{freeform_show.dj}"
- else
  .show_name
    = link_to freeform_show.name, freeform_show
  .show_with
    with
    = link_to freeform_show.dj, freeform_show.dj

app/views/freeform_shows/show.html.haml
- content_for :host do
  %h3 Your Host
  .rotating-hosts
    .tiled.rotating-host
      =render @freeform_show.dj
- title "#{@freeform_show.name}"
- subtitle raw "#{@freeform_show.description.gsub("\r\n\r\n", '<br />')}"
- headline "#{@freeform_show.name}"
- back_link link_to "Back to Schedule", semester_path(@freeform_show.semester)
= content_for :sidebar do
  - if dj_signed_in? && current_dj.can_update?(@freeform_show)
    =render 'form'
  - else
    =content_for :host



- unless @freeform_show.website.blank?
  .show-website
    %cite
      = @freeform_show.unambiguous_name
    has its own website:
    = link_to @freeform_show.website_name, @freeform_show.website
- if dj_signed_in? && current_dj.can_update?(@freeform_show)
  =content_for :host
%h3 Episodes
.tiles
  - @episodes.each do |episode|
    .showinfo.tile
      %p
        = episode.date_string
        %br
        = episode.just_time_string
      -if episode.past?
        %p.show-instance-links
          =link_to "#{episode.songs.count} #{"song".pluralize(episode.songs.count)}",
            episode_songs_path(episode)
      %p.with
        =with(episode) if episode.subbed_for?
        &nbsp;